### ISSUE TITLE
Use GitHub organization for hext repos

### ISSUE THREAD

**Issue by impredicative** [html-extract/hext#10]
Please consider using a free GitHub organization for the various public hext related repos that are currently under your account. Thanks.

**Comment by impredicative** [comment]
FWIW, you will have the option of configuring the visibility of your membership as either "public" or "private". This option would become available at https://github.com/orgs/<HEXT-ORG-NAME>/people/thomastrapp

**Comment by thomastrapp** [comment]
That might be overkill, but yeah, why not :)

I have created the org https://github.com/html-extract and will move 3 repositories to this organization in the coming days:
* https://github.com/thomastrapp/hext
* https://github.com/thomastrapp/hext-on-websockets
* https://github.com/thomastrapp/hext-website

**Comment by thomastrapp** [comment]
I've transferred the repositories and updated all URLs to point to the new org, e.g. Hext is now at https://github.com/html-extract/hext. Which actually looks a bit less amateurish, than the old URLs :)

Old URLs do not need to be updated: Github is kind enough to forward them to the new org.

Thank you for your input.
