### ISSUE TITLE
Handling unknown elements?

### ISSUE THREAD

**Issue by yinleon** [html-extract/hext#12]
First off: thank you for creating & maintaining this software!

I am having an issue with custom HTML elements.
My use case involves HTML like this:
```
<custom-tag>
   <div>Text</div>
</custom-tag>
```

I am unsure how to approach this!
I get an error when I try the extractor on your homepage:
`Error: Unknown HTML tag 'custom-tag' at line 4, char 18:`

**Comment by brandonrobertz** [comment]
Gumbo doesn't like custom elements (they're technically invalid HTML5 documents) and does funny things, from what I can tell. @thomastrapp will probably have a better insight as to whether there's something we can do about it, though.

**Comment by thomastrapp** [comment]
Custom HTML-tags are supported in the current `master` branch, but unfortunately I haven't made a release yet.

The next release will support custom tags. For example, the rule `<custom-tag @text:x />` will match the following HTML:
```html
<custom-tag>
   <div>Text</div>
</custom-tag>
```

A workaround is to use the `*` tag which matches any HTML-tag. For example, `<* id="main"  @text:x />` will match the following HTML:
```html
<custom-tag id="main">
   <div>Text</div>
</custom-tag>
```

I will try to publish a new release within a week, or thereabouts. I'll let you know, once it is ready.
If you have the time and feel adventurous, you can build the latest master branch of Hext from source, see [here](https://hext.thomastrapp.com/download#building-hext) and [here](https://hext.thomastrapp.com/download#building-python-hext).

Thank you for your interest in Hext!

**Comment by thomastrapp** [comment]
@brandonrobertz To my surprise, Gumbo handles unknown tags just fine. In fact it has no issues parsing XML files. It will be possible to use Hext for RSS feeds and what not, which is a nice bonus.

**Comment by brandonrobertz** [comment]
Okay that's excellent news! I know Gumbo can handle unknown tags, but I was under the impression that you have to do things manually to handle certain cases.

If you need any help getting a release together, LMK.

**Comment by thomastrapp** [comment]
Custom/Unknown tags are now supported on all Hext releases
https://github.com/html-extract/hext/releases/tag/v0.8.3

@yinleon Thank you for reporting this issue! If you have questions, feel free to reopen or comment.
