### ISSUE TITLE
Help scraping entries from Facebook AI Blog

### ISSUE THREAD

**Issue by impredicative** [html-extract/hext#15]
I could use help scraping the links and titles for each result from the source of https://ai.facebook.com/blog/ .

The following gives me the first entry only:
```
        <a href:prepend("https://ai.facebook.com"):link><span><div><div>
            <h2 @text:title></h2>
        </div></div></span></a>
```
Example:
```json
{
  "link": "https://ai.facebook.com/blog/powered-by-ai-turning-any-2d-photo-into-3d-using-convolutional-neural-nets/",
  "title": "Powered by AI: Turning any 2D photo into 3D using convolutional neural nets"
}
```

The following gives me the next two entries:
```
        <a href:link><div><div><div><div>
            <h4 @text:title></h4>
        </div></div></div></div></a>
```
Example:
```json
{
  "link": "https://ai.facebook.com/blog/using-radioactive-data-to-detect-if-a-data-set-was-used-for-training/",
  "title": "Using ‘radioactive data’ to detect if a data set was used for training"
}
```

The following gives me all the correct links but not all the correct titles:
```
        <a href^="https://ai.facebook.com/blog/" href:link @text:title />
```

How do I get all results, or is this something that hext is not capable of? Thanks.

**Comment by thomastrapp** [comment]
Interesting. The page source looks like they are trying to complicate scraping.

The following will extract 12 blog posts from https://ai.facebook.com/blog/ for me:
```HTML
<div>
  <div>
    <div>
      <h4:only-child @text:title />
    </div>
  </div>
  <div>
    <div:nth-child(2)>
      <div>
        <a href:link />
      </div>
    </div>
  </div>
</div>
```

```SHELL
$ htmlext facebook-ai.hext <(curl https://ai.facebook.com/blog/) | wc -l
12
```

**Comment by thomastrapp** [comment]
I just realized you tried to capture the three articles at the top of the page.
In that case, I'd recommend using multiple hext templates.

If there ever is a "Hext Version 2", I want to add a mechanism that simplifies problems like these.

For example, I'd like to make the following possible:
```
<a href:link>
  # "inner" hext template (enclosed in braces) that is
  # contained anywhere inside an <a>:
  {
    <* class="heading" @text:heading />
  }
</a>
```

**Comment by impredicative** [comment]
Remarkable. Thank you. I look forward to v2 but there is no rush from me. If you'd like to see several of my other uses of hext, they're under the prefix "`hext: `" [here](https://github.com/impredicative/freenode-bots/blob/master/irc-rss-feed-bot/config.yaml).
