### ISSUE TITLE
Add wheels for Python 3.9

### ISSUE THREAD

**Issue by thomastrapp** [html-extract/hext#18]
https://www.python.org/downloads/release/python-390/

When done, remove CI skip for version 3.9 introduced in commit https://github.com/html-extract/hext/commit/b858d58cfa4a61a0700e106a063d96e2c863a351

**Comment by impredicative** [comment]
Hello. This issue is not urgent for me, but it would be nice to have in the next few months.

Python 3.9 has easier type annotations. It also has `str.removeprefix` and `str.removesuffix` which are nice, making it a preferred Python version.

**Comment by thomastrapp** [comment]
I will have a release ready soon

**Comment by thomastrapp** [comment]
Hext is now available for Python 3.9 on Linux.

Requirements:
* Pip version 19.3 or later
* Support for the platform compatibility tag 'manylinux2014_x86_64' (check with: `pip debug --verbose | grep manylinux2014_x86_64`)

@impredicative Thank you for pushing the issue!
