### ISSUE TITLE
updated release

### ISSUE THREAD

**Issue by thezoggy** [html-extract/hext#20]
I saw you updated this for py3.9,
https://github.com/html-extract/hext/issues/18

has that version been posted to pypi?

github latest release is from 2019 - v0.8.3
pypi latest is 2020 - v0.2.5
npm latest is - v10.0.5

**Comment by thomastrapp** [comment]
Hext for Python 3.9 is on Pypi -- but only for the platform tag `manylinux2014_x86_64`. Let me know if you need hext for a different system or architecture.

hext-0.2.5-cp39-cp39-manylinux2014_x86_64.whl
https://pypi.org/project/hext/#files

**Comment by brandonrobertz** [comment]
I've noticed that the python 3.8 version for Mac OS is also missing. I have access to a mac now so I can help with testing/building or anything, just LMK.

**Comment by thomastrapp** [comment]
@brandonrobertz 
> I've noticed that the python 3.8 version for Mac OS is also missing.

There is a Mac OS release for python 3.8 ( hext-0.2.5-cp38-cp38-macosx_10_11_x86_64.whl ).

I assume you actually meant python 3.9, for which there indeed is no release.
I'll have a release ready soon.

I have previously built the releases on an old and dusty Macbook. Instead, I will try to have automated builds with Github Actions in the future.

**Comment by thomastrapp** [comment]
@brandonrobertz 
> I've noticed that the python 3.8 version for Mac OS is also missing.

There is a Mac OS release for python 3.8 ( hext-0.2.5-cp38-cp38-macosx_10_11_x86_64.whl ).

I assume you actually meant python 3.9, for which there indeed is no release.
I'll have a release ready soon.

I have previously built the releases on an old and dusty Macbook. Instead, I will try to have automated builds with Github Actions in the future.

**Comment by brandonrobertz** [comment]
> @brandonrobertz
> 
> > I've noticed that the python 3.8 version for Mac OS is also missing.
> 
> There is a Mac OS release for python 3.8 ( hext-0.2.5-cp38-cp38-macosx_10_11_x86_64.whl ).
> 
> I assume you actually meant python 3.9, for which there indeed is no release.
> I'll have a release ready soon.


Hi yes! My bad. I did something stupid and labeled my venv 3.8, when in fact, it was a python 3.9 environment. Thanks for your work on this Thomas, you're a champ.

**Comment by thomastrapp** [comment]
Hext is now available for Python 3.9 on Mac OS, i.e. `pip install hext` will work with Python 3.9.
The release was built with Github actions. Supporting new Python versions on Mac OS will be dead simple in the future.

I'm closing this issue - But feel free to open a new issue if you think Hext is missing for some other OS or language.

Thanks!
