### ISSUE TITLE
Arbitrary Nested Hext Templates

### ISSUE THREAD

**Issue by brandonrobertz** [html-extract/hext#22]
Hello from the west coast. So I've been using hext a ton over the past couple years now, building scrapers for all kinds of journalistic work. For the most part it works great, especially combined with the easy-to-use [web hext template builder](https://github.com/brandonrobertz/hextractor).

One thing that's been coming up more frequently is sites that either try to frustrate web scraping attempts by arbitrary obfuscation/garbage divs, or sometimes just really poor quality/hand-crafted HTML from small government entities. DOMs that look like this:

```
<div class="list">
  <div class="item">Heading
    <p>Item one</p>
  </div>

  <div class="item"><div>Title 2</div>
    <p>Item two</p>
  </div>

  <div class="item">Title 3
    <div>
      <div>
        <p>Item Three</p>
      </div>
    </div>
  </div>
</div>
```

Let's say we want to get the contents of the `<p>` tag from every item in the list. A nested rule would be the simplest, most robust method to build an extractor for such DOMs, IMO.

I still think hext is the most change-resistant way to build extractors for websites, but the lack of a way to specify arbitrary-depth ancestor matching rules limits the ways hext can be used directly.

This has been discussed in other issues: https://github.com/html-extract/hext/issues/15 and https://github.com/html-extract/hext/issues/16

I really feel like this is the missing link for hext, so I wanted to ask about what would be required to get something like this working. I'd be willing to try and get some work done in this direction if I could get pointed in the right direction. The solution posed in #15 really seems like the ideal method:

```
<a href:link>
  # "inner" hext template (enclosed in braces) that is
  # contained anywhere inside an <a>:
  {
    <h1 @text:heading />
  }
</a>
```

Is this a grammar change? Or do we accomplish this via code, extracting bracketed hext templates and applying them recursively to the results? Some other way?

Here's to Hext in 2022! 🥂

**Comment by thomastrapp** [comment]
Nested Rules
---

```html
<a>
  {
    <b/>
  }
  <c/>
</a>
```

Rules get a new member: Nested Rules. `<b/>` would be the one and only Nested Rule of `<a>` in the above template. Nested Rules are regular Rules, but are treated differently when matching rules against nodes.

A Rule matches a node if all its Nested Rules are successfully matched against the content of the node, i.e. node.innerHTML.

Nested Rules have no order: `{<b/>}` can be matched before, after or even in nodes matching `<c>`.
In other words, the following two hext templates are equivalent in regards to matching:

```html
<a>
  <h1 @text:title />
  {
    <span @text:author />
  }
</a>
```

```html
<a>
  {
    <span @text:author />
  }
  <h1 @text:title />
</a>
```


Worst case performance
----

```html
<*>
  {
    <*>
      {
        <*/>
      }
    <*/>
  }
</*>
```

This would result in roughly n^3 comparisons, where n is the amnount of nodes in a document. That's a problem.

And a help in denial-of-service attacks, when accepting untrusted hext. This could be mitigated by a configuration option. Maybe something like "abort after doing x amount of work". IIRC, regex engines have similar protections.


Data extraction
----

##### Simple example

```html
<div class:class>
  {
    <p @text:content />
  }
</div>
```

```html
<div class="list1">
  <div class="item"><p>One</p>  </div>
  <div class="item"><p>Two</p>  </div>
  <div class="item"><p>Three</p></div>
</div>
<div class="list2">
  <div class="item"><p>Four</p> </div>
  <div class="item"><p>Five</p> </div>
  <div class="item"><p>Six</p>  </div>
</div>
```

```json
{
  "class": "list1",
  "content": ["One","Two","Three"]
}
{
  "class": "list2",
  "content": ["Four","Five","Six"]
}
```

##### Multiple nested rules

```html
<body>
  {
    <p @text:content />
  }
  {
    <a href:href />
  }
</body>
```

```html
<body>
  <div> <p>P1 <a href="p1-href"></a></p> </div>
  <div> <p>P2 <a href="p2-href"></a></p> </div>
</body>
```

```json
{
  "content": ["P1", "P2"],
  "href": ["p1-href", "p2-href"]
}
```

Todo: More examples.


Scope
---

* [Rule.cpp](https://github.com/html-extract/hext/blob/47c9525f114fe8acb966bcd4859627d31e17995d/libhext/src/Rule.cpp): New member `nested_`, ability to add nested rules and iterate over them
* [RuleMatching.cpp](https://github.com/html-extract/hext/blob/47c9525f114fe8acb966bcd4859627d31e17995d/libhext/src/RuleMatching.cpp): Match nested rules
* [hext-machine.rl](https://github.com/html-extract/hext/blob/47c9525f114fe8acb966bcd4859627d31e17995d/libhext/ragel/hext-machine.rl): Add syntax, Rule tree building
* Unit tests, blackbox tests
* Documentation
* Syntax highlighting for ACE and Vim


So far this looks like a non-breaking change (in regards to already written hext templates). I hope I didn't miss anything crucial.


This might actually work :) I need to sleep on this a bit.

**Comment by brandonrobertz** [comment]
Wow this is incredible progress! If you want help testing or writing unit tests, or any other task, let me know.

**Comment by thomastrapp** [comment]
Current master supports nested rules (63339e03e44e0b833461397c347c489be7c2b9f2).

I am going to add a way to limit hext's resource usage, specifically for [hext-on-websockets](https://github.com/html-extract/hext-on-websockets).

For example, this consumes about 300MB of memory at peak:
```sh
\time --verbose htmlext \
  <(echo '<* @inner-html:a>{<* @inner-html:b>{<* @inner-html:c>{<* @inner-html:d>{<* @inner-html:e>{<* @inner-html:f>{<*/>}</*>}</*>}</*>}</*>}</*>}</*>') \
  <(curl https://news.ycombinator.com/) > /dev/null
```

I'm thinking about adding a parameter to [`Rule::extract(html)`](https://github.com/html-extract/hext/blob/e7d7e8d22b811dade9b64969dc8ed062f6296684/libhext/include/hext/Rule.h#L239-L245), something like:
`Rule::extract(html, int max_nested_recursion = 0)`
This parameter controls how often nested rules can traverse the HTML tree. I am not sure about the details, yet.
The default value disables throttling.

After solving this problem, I will publish new releases and update the documentation.

Nested rules are a great addition to hext. Thank you for the well written feature request.

**Comment by brandonrobertz** [comment]
Great work! I'm readying everything for updates to [hext-emscripten](https://github.com/html-extract/hext-emscripten) and my [hextractor](https://github.com/brandonrobertz/hextractor). Will be testing!

**Comment by thomastrapp** [comment]
The new pypi package v0.3.0 is built from hext v1.0.0 and currently available for:
* manylinux2014: Python 3.5 - 3.9 (3.10 will follow soon)
* macosx: Python 3.6 - 3.10

Todo:
* node/npm packages
* Support for "max_searches" parameter in language bindings

**Comment by thomastrapp** [comment]
All done!
I will probably improve the documentation at a later date.

Thank you for using hext - Let me know if there is anything missing.

**Comment by brandonrobertz** [comment]
As always I'm impressed! I'm going to update hextractor and the other libraries and if I find any issues I'll open a new ticket. Thanks so much! 🦾
