### ISSUE TITLE
TypeError: Wrong number or type of arguments for overloaded function 'Rule_extract'

### ISSUE THREAD

**Issue by impredicative** [html-extract/hext#27]
With Python 3.12, `hext.Rule('').extract('')` gives the error:

```
  File "python3.12/site-packages/hext/__init__.py", line 139, in extract
    return _hext.Rule_extract(self, html, max_searches)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Wrong number or type of arguments for overloaded function 'Rule_extract'.
  Possible C/C++ prototypes are:
    Rule::extract(Html const &,std::uint64_t) const
    Rule::extract(Html const &) const
```

I am of course also getting this error with a more real-life example. At this time I cannot use hext for anything new.

**Comment by thomastrapp** [comment]
Rule.extract does not accept a string, only `hext.Html`.

```python
import hext
rule = hext.Rule("<a href:link/>")
# (1) Ok, the argument for extract is of type hext.Html
results = rule.extract(hext.Html("""<a href="b"></a>"""))
# (2) Error, the argument for extract is of type string:
results = rule.extract("""<a href="b"></a>""")
```

If this was possible in a previous version of Hext (≥1.0.0), please let me know, as this would be a breaking change in the API.

The error message is unfortunately very unhelpful, and I will fix that in a future release with #28.

Thank you for creating this issue.

**Comment by brandonrobertz** [comment]
> If this was possible in a previous version of Hext (≥1.0.0), please let me know, as this would be a breaking change in the API.

This was not possible in 0.8 (just re-tested to be sure). AFAIK you always needed to pass a Html object.

**Comment by thomastrapp** [comment]
> As an aside, I think there really needs to exist at least one comprehensive page (or tabs) per supported programming language in the documentation. It would contain various necessary examples to train the user to use hext effectively.

I agree and have added another issue for this: #29.
