### ISSUE TITLE
ARM64 wheel required for Linux

### ISSUE THREAD

**Issue by impredicative** [html-extract/hext#41]
I am trying to install `hext` in a Linux devcontainer while on my Mac. The error I get is:

```
(newssurvey) vscode ➜ /workspaces/newssurvey (master) $ rye sync
Reusing already existing virtualenv
Generating production lockfile: /workspaces/newssurvey/requirements.lock
Generating dev lockfile: /workspaces/newssurvey/requirements-dev.lock
Installing dependencies
  × No solution found when resolving dependencies:
  ╰─▶ Because hext==1.0.12 has no wheels with a matching platform tag and you require hext==1.0.12, we can conclude that your requirements are unsatisfiable.
error: Installation of dependencies failed in venv at /workspaces/newssurvey/.venv. uv exited with status: exit status: 1

(newssurvey) vscode ➜ /workspaces/newssurvey (master) $ arch
aarch64
```

It is apparent that this inability to install `hext` is because https://pypi.org/project/hext/1.0.12/#files doesn't list Linux wheels for arm64. I greatly appreciate if this can be resolved.

**Comment by thomastrapp** [comment]
Hext is now available for platform tag "manylinux_2_28_aarch64", i.e.
```shell
pip install hext
```
will work on typical ARM64 linux machines.

These releases are not yet built with Github Actions -- I am waiting for ARM64 support in Github Actions, which will hopefully be ready in the coming months ( tracked in #42 ).

Thank you for your feature request -- Let me know if you have any issues.
